secretsprovider: gcpkms://projects/remix-template/locations/us-central1/keyRings/remix-template-keyring/cryptoKeys/remix-template-key
encryptedkey: CiQAaryhKr3bweRjkgJjofnqJ2ZvXR38cPjMaSIG6iJ0EwfvDZkSSQCsUcM0WAyUU/7PFlVuSkeFd4R1Mjr4K1glO8cslmkARCvXzEzhzN3P3ZZsERxpqUG4yj9agjjkimgKmc6GRp64NRqjAMJ3NtY=
config:
  gcp:project: remix-template
  remix-template:FIREBASE_API_KEY:
    secure: v1:HZ8CD1DqcrmH6cSg:oWqrZvpLDH7YAPIxeu9WcULXocIXefufM7Kow2OMa0fdWEuLkH7XXrWh3/Xq1Zc1NRaMhSe4EA==
  remix-template:FIREBASE_AUTH_DOMAIN:
    secure: v1:dJOx1S0T2ILL+ftK:kg+qIstZ/blYEhIniNMQ4Eoi6u/gQUi/imEgZ894ArTsXcnnzLsk6TXznhAkRA==
  remix-template:POSTGRES_PASSWORD:
    secure: v1:pbs5UCWWMYLb4g+S:s9tI9v3ZwO8sMA1m/HPGYfSmFtoU/tAderdZ0Cp44aBtCQsCyMaHXL/ttyMq2Atw2toZwIWuPls=
  remix-template:POSTGRES_USER:
    secure: v1:5nsMvqPlalLawtih:FrPRdiF1KUrXI3/2SZo9tO1chXJM6DX3vZg=
  remix-template:SESSION_STORAGE_SECRET:
    secure: v1:UUmw9b0FixfpJ90A:RURxYL3GFdBpIbuoANHT+JPBdXh3HPoCVkFHyBMdPCqCMINFfWH1tLqTnai+xk1OJetXfQUDE6w=
