---
name: Main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Test
        run: |
          yarn install --frozen-lockfile
          yarn test

  deploy:
    runs-on: ubuntu-latest
    needs: ['test']

    env:
      BOS_ENV: ${{ secrets.BOS_ENV }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Test
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn deploy
