---
name: Pull Request

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Test
        run: |
          yarn install --frozen-lockfile
          yarn test

  test-e2e:
    runs-on: ubuntu-latest

    env:
      BOS_JWT_SECRET: 'ci-secret'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Test e2e
        run: |
          yarn install --frozen-lockfile
          yarn test:e2e
